wandb_version: 1

_name_or_path:
  desc: null
  value: bert-base-cased
_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    python_version: 3.10.6
    start_time: 1670757669.39255
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 7
      - 13
      - 23
      4: 3.10.6
      5: 0.13.6
      6: 4.25.1
      8:
      - 1
      - 4
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - BertForMaskedLM
attention_probs_dropout_prob:
  desc: null
  value: 0.1
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
classifier_dropout:
  desc: null
  value: null
cross_attention_hidden_size:
  desc: null
  value: null
data_seed:
  desc: null
  value: None
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: null
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 128
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: None
evaluation_strategy:
  desc: null
  value: epoch
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
full_determinism:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: None
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hidden_act:
  desc: null
  value: gelu
hidden_dropout_prob:
  desc: null
  value: 0.1
hidden_size:
  desc: null
  value: 768
hub_model_id:
  desc: null
  value: None
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': O
    '1': B-AerospaceManufacturer
    '10': B-Drink
    '11': B-Facility
    '12': B-Food
    '13': B-HumanSettlement
    '14': B-MedicalProcedure
    '15': B-Medication/Vaccine
    '16': B-MusicalGRP
    '17': B-MusicalWork
    '18': B-ORG
    '19': B-OtherLOC
    '2': B-AnatomicalStructure
    '20': B-OtherPER
    '21': B-OtherPROD
    '22': B-Politician
    '23': B-PrivateCorp
    '24': B-PublicCorp
    '25': B-Scientist
    '26': B-Software
    '27': B-SportsGRP
    '28': B-SportsManager
    '29': B-Station
    '3': B-ArtWork
    '30': B-Symptom
    '31': B-Vehicle
    '32': B-VisualWork
    '33': B-WrittenWork
    '34': I-AerospaceManufacturer
    '35': I-AnatomicalStructure
    '36': I-ArtWork
    '37': I-Artist
    '38': I-Athlete
    '39': I-CarManufacturer
    '4': B-Artist
    '40': I-Cleric
    '41': I-Clothing
    '42': I-Disease
    '43': I-Drink
    '44': I-Facility
    '45': I-Food
    '46': I-HumanSettlement
    '47': I-MedicalProcedure
    '48': I-Medication/Vaccine
    '49': I-MusicalGRP
    '5': B-Athlete
    '50': I-MusicalWork
    '51': I-ORG
    '52': I-OtherLOC
    '53': I-OtherPER
    '54': I-OtherPROD
    '55': I-Politician
    '56': I-PrivateCorp
    '57': I-PublicCorp
    '58': I-Scientist
    '59': I-Software
    '6': B-CarManufacturer
    '60': I-SportsGRP
    '61': I-SportsManager
    '62': I-Station
    '63': I-Symptom
    '64': I-Vehicle
    '65': I-VisualWork
    '66': I-WrittenWork
    '7': B-Cleric
    '8': B-Clothing
    '9': B-Disease
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 3072
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    B-AerospaceManufacturer: 1
    B-AnatomicalStructure: 2
    B-ArtWork: 3
    B-Artist: 4
    B-Athlete: 5
    B-CarManufacturer: 6
    B-Cleric: 7
    B-Clothing: 8
    B-Disease: 9
    B-Drink: 10
    B-Facility: 11
    B-Food: 12
    B-HumanSettlement: 13
    B-MedicalProcedure: 14
    B-Medication/Vaccine: 15
    B-MusicalGRP: 16
    B-MusicalWork: 17
    B-ORG: 18
    B-OtherLOC: 19
    B-OtherPER: 20
    B-OtherPROD: 21
    B-Politician: 22
    B-PrivateCorp: 23
    B-PublicCorp: 24
    B-Scientist: 25
    B-Software: 26
    B-SportsGRP: 27
    B-SportsManager: 28
    B-Station: 29
    B-Symptom: 30
    B-Vehicle: 31
    B-VisualWork: 32
    B-WrittenWork: 33
    I-AerospaceManufacturer: 34
    I-AnatomicalStructure: 35
    I-ArtWork: 36
    I-Artist: 37
    I-Athlete: 38
    I-CarManufacturer: 39
    I-Cleric: 40
    I-Clothing: 41
    I-Disease: 42
    I-Drink: 43
    I-Facility: 44
    I-Food: 45
    I-HumanSettlement: 46
    I-MedicalProcedure: 47
    I-Medication/Vaccine: 48
    I-MusicalGRP: 49
    I-MusicalWork: 50
    I-ORG: 51
    I-OtherLOC: 52
    I-OtherPER: 53
    I-OtherPROD: 54
    I-Politician: 55
    I-PrivateCorp: 56
    I-PublicCorp: 57
    I-Scientist: 58
    I-Software: 59
    I-SportsGRP: 60
    I-SportsManager: 61
    I-Station: 62
    I-Symptom: 63
    I-Vehicle: 64
    I-VisualWork: 65
    I-WrittenWork: 66
    O: 0
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_eps:
  desc: null
  value: 1.0e-12
learning_rate:
  desc: null
  value: 2.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: passive
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./results/runs/Dec11_11-21-05_MacBook-Pro
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_position_embeddings:
  desc: null
  value: 512
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: None
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: bert
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 12
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_hidden_layers:
  desc: null
  value: 12
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 30
optim:
  desc: null
  value: adamw_hf
optim_args:
  desc: null
  value: None
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ./results
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 128
per_device_train_batch_size:
  desc: null
  value: 128
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
position_embedding_type:
  desc: null
  value: absolute
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
ray_scope:
  desc: null
  value: last
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: ./results
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: None
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: None
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: None
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 128
transformers_version:
  desc: null
  value: 4.25.1
type_vocab_size:
  desc: null
  value: 2
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 28996
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.01
xpu_backend:
  desc: null
  value: None
